### ISSUE TITLE
`go get` does not work

### ISSUE THREAD

**Issue by h8liu** [romanyx/mdopen#2]
```
$ go get gopkg.in/romanyx/mdopen.v1
go/src/gopkg.in/romanyx/mdopen.v1/mdopen.go:13:2: use of internal package not allowed
```

this is because `gopkg.in`'s version solution is not compatible with go language's import scheme on `internal` packages.

you would need to rewrite the import paths for v1 tags..

**Comment by h8liu** [comment]
detected when by [smallrepo.com](https://smallrepo.com).

build log: https://smallrepo.com/builds/20180507-052927-2bda40e3

**Comment by romanyx** [comment]
Thanks for the issue, you can do `go get github.com/romanyx/mdopen` for now, while I'm fixing it.

**Comment by romanyx** [comment]
https://github.com/romanyx/mdopen/pull/3
