### ISSUE TITLE
Include LaTeX support

### ISSUE THREAD

**Issue by lssimoes** [romanyx/mdopen#4]
Although not in the [initial sane](https://daringfireball.net/projects/markdown/syntax) specification, several Markdown specifications (such as [Pandoc](http://pandoc.org/MANUAL.html#math)'s) use LaTeX to render math equations.

Maybe it is a nice idea for this package to support LaTeX as well. For example, using [KaTeX](https://github.com/Khan/KaTeX)

**Comment by romanyx** [comment]
https://github.com/romanyx/mdopen/compare/master...feature/latex_support

LaTeX math equation quoted by `$` for inline, and `$$` for a block.

**Comment by romanyx** [comment]
https://github.com/romanyx/mdopen/pull/5 LaTeX math equation quoted by `$` for inline, and `$$` for a block.
