### ISSUE TITLE
When are temp files created by mdopen cleaned up?

### ISSUE THREAD

**Issue by mario-grgic** [romanyx/mdopen#6]
mdopen created html version of markdown in system TMP directory and opens it in default browser. But the temp file is never cleaned up?

Should mdopen delete the generated temp file after it is successfully opened in the browser?

**Comment by romanyx** [comment]
Hey, there is no ability to check if the browser already open or is still opening the file. The previous files could be deleted at every mdopen launch, but should this be added as the tmp dir will be cleaned up after each system reboot?

**Comment by mario-grgic** [comment]
macOS's open command has -W option that allows open to wait until the application it opened is closed. This could be leveraged to clean up temp files, at least on this platform.

Otherwise, perhaps waiting some reasonable time (1 second?) and then purging the temp file is enough. 

In the worst case, cleaning up on restart is acceptable. I was not sure this is happening (rarely shut down/restart).
